DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_item_seo;
CREATE TABLE /*TABLE_PREFIX*/t_item_seo (
seo_item_id INT UNSIGNED NOT NULL,
seo_title VARCHAR(500),
seo_desc VARCHAR(800),
seo_keywords VARCHAR(500),

PRIMARY KEY (seo_item_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';

DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_pages_seo;
CREATE TABLE /*TABLE_PREFIX*/t_pages_seo (
seo_page_id INT UNSIGNED NOT NULL,
seo_title VARCHAR(500),
seo_desc VARCHAR(800),
seo_keywords VARCHAR(500),

PRIMARY KEY (seo_page_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';

DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_categories_seo;
CREATE TABLE /*TABLE_PREFIX*/t_categories_seo (
seo_category_id INT UNSIGNED NOT NULL,
seo_title VARCHAR(500),
seo_desc VARCHAR(800),
seo_keywords VARCHAR(500),

PRIMARY KEY (seo_category_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';

DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_country_seo;
CREATE TABLE /*TABLE_PREFIX*/t_country_seo (
seo_country_code CHAR(2) NOT NULL,
seo_title VARCHAR(500),
seo_desc VARCHAR(800),
seo_keywords VARCHAR(500),

PRIMARY KEY (seo_country_code)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';

DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_region_seo;
CREATE TABLE /*TABLE_PREFIX*/t_region_seo (
seo_region_id INT UNSIGNED NOT NULL,
seo_title VARCHAR(500),
seo_desc VARCHAR(800),
seo_keywords VARCHAR(500),

PRIMARY KEY (seo_region_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';

DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_links_seo;
CREATE TABLE /*TABLE_PREFIX*/t_links_seo (
seo_link_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
seo_title VARCHAR(500),
seo_href VARCHAR(800),
seo_footer VARCHAR(10),
seo_rel VARCHAR(10),

PRIMARY KEY (seo_link_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';

DROP TABLE IF EXISTS /*TABLE_PREFIX*/t_links_rec_seo;
CREATE TABLE /*TABLE_PREFIX*/t_links_rec_seo (
seo_link_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
seo_href_to VARCHAR(500),
seo_href_from VARCHAR(500),
seo_contact VARCHAR(100),
seo_status INT(1),

PRIMARY KEY (seo_link_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET 'UTF8' COLLATE 'UTF8_GENERAL_CI';